In [ ]:
import math
import numpy as np

act = lambda x: 1 / (1 + math.e ** -x)

x = np.array([.05, .10]).T

w1 = np.array([
    [.15, .20],
    [.25, .30]
])
b1 = 0.35
w2 = np.array([
    [.40, .45],
    [.50, .55]
])
b2 = 0.60

y = np.array([.01, .99]).T

hl1 = act(w1 @ x + b1)

y_p = act(w2 @ hl1 + b2)
y_p

In [13]:
cost = (y - y_p)
cost

array([-0.49,  0.49])

In [14]:
mse = 1 / 2 * (y - y_p) @ (y - y_p).T
mse

0.24009999999999998

In [15]:
dact = lambda x: act(x) * (1 - act(x))
lam = 0.3
new_w2 = w2.copy()
de_dy = -cost
for i, r in enumerate(w2):
    for j, w in enumerate(r):
        dw = [[0.0, 0.0], [0.0, 0.0]]
        dw[i][j] = 1
        dy = np.array([0.0, 0.0])
        dy[i] = dact(w2 @ hl1 + b2) @ (dw @ hl1 + 0)
        dmse = de_dy @ dy
        new_w2[i][j] -= dmse * lam
new_w2

array([[0, 0],
       [0, 0]])

In [16]:
new_w1 = w1.copy()
dy_dh = dact(w2 @ hl1 + b2) * w2
for i, r in enumerate(w1):
    for j, w in enumerate(r):
        dw = [[0.0, 0.0], [0.0, 0.0]]
        dw[i][j] = 1
        dhl1 = np.array([0.0, 0.0])
        dhl1[i] = dact(w1 @ x + b1) @ (dw @ x + 0)
        dy = dy_dh @ dhl1
        dmse = de_dy @ dy
        new_w1[i][j] -= dmse * lam
new_w1


array([[0, 0],
       [0, 0]])

In [17]:
new_b2 = b2
dy = np.array([0.0, 0.0])
dy[i] = dact(w2 @ hl1 + b2) @ (np.array([1.0, 1.0]))
dmse = de_dy @ dy
new_b2 -= dmse * lam
new_b2

0.0735

In [18]:
new_b1 = b1
dhl1 = np.array([0.0, 0.0])
dhl1[i] = dact(w1 @ x + b1) @ (np.array([1.0, 1.0]))
dy = dy_dh @ dhl1
dmse = de_dy @ dy
new_b1 -= dmse * lam
new_b1

0.0

In [19]:
w1=new_w1
b1=new_b1
w1=new_w2
b1=new_b2

hl1 = act(w1 @ x + b1)

y_p = act(w2 @ hl1 + b2)
y_p

array([0.5, 0.5])

In [20]:
cost = (y - y_p)
cost

array([-0.49,  0.49])

In [21]:
mse = 1 / 2 * (y - y_p) @ (y - y_p).T
mse



0.24009999999999998

In [22]:

{
  'w1': [[0.14987287, 0.19974574],
         [0.2498643, 0.2997286]],
  'b1': 0.34456420672061516,

  'w2': [[0.37534989, 0.42519971],
         [0.50678076, 0.55682207]],
  'b2': 0.6235951757709365,

  'mse': 0.30404065487865817
 }

{'w1': [[0.14987287, 0.19974574], [0.2498643, 0.2997286]],
 'b1': 0.34456420672061516,
 'w2': [[0.37534989, 0.42519971], [0.50678076, 0.55682207]],
 'b2': 0.6235951757709365,
 'mse': 0.30404065487865817}